---
version: '3'
services:
  jenkins:
    build: ./jenkins/
    container_name: jenkins
    restart: always
    environment:
      - TZ=Asia/Shanghai
    ports:
      - '8080:8080'
      - '50000:50000'
    volumes:
      - './Jenkins/jenkins_home:/var/jenkins_home'